// Traduce nombres de ejercicios EN→ES por frases y tokens. El dataset solo trae
// el nombre en inglés; aquí lo pasamos a un español legible y consistente.
// Estrategia: 1) extraer el equipo (va al final como "con …"), 2) traducir el
// núcleo del movimiento por frases (coincidencia más larga primero), 3) traducir
// las palabras sueltas restantes, 4) las desconocidas se quedan como están.

// Equipo → sufijo. Se detecta y se mueve al final del nombre.
const EQUIPO = [
  [/\bez[- ]?bar(bell)?\b/g, 'con barra Z'],
  [/\bsz[- ]?bar\b/g, 'con barra Z'],
  [/\bolympic barbell\b/g, 'con barra olímpica'],
  [/\btrap bar\b/g, 'con barra hexagonal'],
  [/\bbarbell\b/g, 'con barra'],
  [/\bdumbbells\b/g, 'con mancuernas'],
  [/\bdumbbell\b/g, 'con mancuerna'],
  [/\bkettlebell\b/g, 'con pesa rusa'],
  [/\bsmith machine\b/g, 'en máquina Smith'],
  [/\bsmith\b/g, 'en máquina Smith'],
  [/\bsled\b/g, 'en máquina de trineo'],
  [/\bcable\b/g, 'en polea'],
  [/\bpulley\b/g, 'en polea'],
  [/\blandmine\b/g, 'con landmine'],
  [/\bhammer\b/g, 'en máquina Hammer'],
  [/\bleverage machine\b/g, 'en máquina'],
  [/\blever\b/g, 'en máquina'],
  [/\bmachine\b/g, 'en máquina'],
  [/\bresistance band\b/g, 'con banda'],
  [/\bband\b/g, 'con banda'],
  [/\bmedicine ball\b/g, 'con balón medicinal'],
  [/\bstability ball\b/g, 'con fitball'],
  [/\bswiss ball\b/g, 'con fitball'],
  [/\bball\b/g, 'con fitball'],
  [/\bbosu\b/g, 'en Bosu'],
  [/\bsuspension\b/g, 'en suspensión'],
  [/\bab wheel\b/g, 'con rueda abdominal'],
  [/\bwheel\b/g, 'con rueda abdominal'],
  [/\bab roller\b/g, 'con rueda abdominal'],
  [/\btowel\b/g, 'con toalla'],
]

// Frases de movimiento (coincidencia más larga primero). Se aplican al texto ya
// sin el equipo. El orden del array importa: lo más específico arriba.
const FRASES = [
  ['romanian deadlift', 'peso muerto rumano'],
  ['stiff leg deadlift', 'peso muerto piernas rígidas'],
  ['stiff-leg deadlift', 'peso muerto piernas rígidas'],
  ['sumo deadlift', 'peso muerto sumo'],
  ['straight leg deadlift', 'peso muerto piernas rígidas'],
  ['deadlift', 'peso muerto'],
  ['bench press', 'press de banca'],
  ['incline bench press', 'press de banca inclinado'],
  ['decline bench press', 'press de banca declinado'],
  ['floor press', 'press en el suelo'],
  ['shoulder press', 'press de hombros'],
  ['military press', 'press militar'],
  ['overhead press', 'press por encima de la cabeza'],
  ['chest press', 'press de pecho'],
  ['leg press', 'prensa de piernas'],
  ['push press', 'push press'],
  ['close grip bench press', 'press de banca agarre cerrado'],
  ['bicep curl', 'curl de bíceps'],
  ['biceps curl', 'curl de bíceps'],
  ['hammer curl', 'curl martillo'],
  ['preacher curl', 'curl predicador'],
  ['concentration curl', 'curl concentrado'],
  ['spider curl', 'curl araña'],
  ['wrist curl', 'curl de muñeca'],
  ['reverse curl', 'curl inverso'],
  ['zottman curl', 'curl Zottman'],
  ['drag curl', 'curl de arrastre'],
  ['leg curl', 'curl femoral'],
  ['lateral raise', 'elevación lateral'],
  ['front raise', 'elevación frontal'],
  ['rear delt raise', 'elevación posterior de hombro'],
  ['rear raise', 'elevación posterior'],
  ['calf raise', 'elevación de gemelo'],
  ['leg raise', 'elevación de piernas'],
  ['knee raise', 'elevación de rodillas'],
  ['triceps extension', 'extensión de tríceps'],
  ['tricep extension', 'extensión de tríceps'],
  ['leg extension', 'extensión de piernas'],
  ['back extension', 'extensión de espalda'],
  ['lat pulldown', 'jalón al pecho'],
  ['pulldown', 'jalón'],
  ['pullover', 'pullover'],
  ['pull up', 'dominada'],
  ['pull-up', 'dominada'],
  ['pullup', 'dominada'],
  ['chin up', 'dominada supina'],
  ['chin-up', 'dominada supina'],
  ['push up', 'flexión'],
  ['push-up', 'flexión'],
  ['pushup', 'flexión'],
  ['sit up', 'abdominal'],
  ['sit-up', 'abdominal'],
  ['situp', 'abdominal'],
  ['upright row', 'remo al mentón'],
  ['bent over row', 'remo inclinado'],
  ['bent-over row', 'remo inclinado'],
  ['pushdown', 'extensión en polea'],
  ['kickback', 'patada de tríceps'],
  ['good morning', 'buenos días'],
  ['hyperextension', 'hiperextensión'],
  ['hip thrust', 'empuje de cadera'],
  ['hip lift', 'elevación de cadera'],
  ['hip abduction', 'abducción de cadera'],
  ['hip adduction', 'aducción de cadera'],
  ['behind the neck', 'tras nuca'],
  ['behind neck', 'tras nuca'],
  ['wide grip', 'agarre ancho'],
  ['close grip', 'agarre cerrado'],
  ['narrow grip', 'agarre estrecho'],
  ['neutral grip', 'agarre neutro'],
  ['reverse grip', 'agarre inverso'],
  ['v bar', 'con barra en V'],
  ['russian twist', 'giro ruso'],
  ['mountain climber', 'escalador'],
  ['jumping jack', 'salto de tijera'],
  ['hack squat', 'sentadilla hack'],
  ['front squat', 'sentadilla frontal'],
  ['split squat', 'sentadilla dividida'],
  ['pistol squat', 'sentadilla pistol'],
  ['goblet squat', 'sentadilla goblet'],
  ['sissy squat', 'sentadilla sissy'],
  ['squat', 'sentadilla'],
  ['lunge', 'zancada'],
  ['plank', 'plancha'],
  ['bridge', 'puente'],
  ['crunch', 'crunch'],
  ['shrug', 'encogimiento de hombros'],
  ['thruster', 'thruster'],
  ['clean and jerk', 'cargada y envión'],
  ['clean', 'cargada'],
  ['snatch', 'arrancada'],
  ['jerk', 'envión'],
  ['burpee', 'burpee'],
  ['dip', 'fondo'],
  ['dips', 'fondos'],
  ['row', 'remo'],
  ['fly', 'aperturas'],
  ['flye', 'aperturas'],
  ['flyes', 'aperturas'],
  ['curl', 'curl'],
  ['press', 'press'],
  ['raise', 'elevación'],
  ['extension', 'extensión'],
  ['twist', 'giro'],
  ['pull', 'jalón'],
  ['push', 'empuje'],
  ['stretch', 'estiramiento'],
  ['hold', 'isometría'],
  ['swing', 'balanceo'],
  ['walk', 'caminata'],
  ['jump', 'salto'],
  ['run', 'carrera'],
  ['step up', 'subida al cajón'],
  ['step-up', 'subida al cajón'],
]

// Palabras sueltas (matices, partes del cuerpo, direcciones).
const PALABRAS = {
  seated: 'sentado',
  standing: 'de pie',
  lying: 'tumbado',
  incline: 'inclinado',
  decline: 'declinado',
  reverse: 'inverso',
  'bent-over': 'inclinado',
  bent: 'inclinado',
  kneeling: 'de rodillas',
  prone: 'boca abajo',
  supine: 'boca arriba',
  assisted: 'asistido',
  weighted: 'con peso',
  alternate: 'alterno',
  alternating: 'alterno',
  single: 'a una',
  one: 'a una',
  two: 'dos',
  double: 'doble',
  wide: 'ancho',
  narrow: 'estrecho',
  close: 'cerrado',
  neutral: 'neutro',
  straight: 'recto',
  bar: 'barra',
  bench: 'banco',
  grip: 'agarre',
  rotational: 'rotacional',
  rotary: 'rotatorio',
  lean: 'inclinado',
  bends: 'flexiones',
  bend: 'flexión',
  raised: 'elevado',
  raises: 'elevaciones',
  curls: 'curls',
  extended: 'extendido',
  circles: 'círculos',
  circular: 'circular',
  cross: 'cruzado',
  crossover: 'cruce',
  crossovers: 'cruces',
  arm: 'brazo',
  arms: 'brazos',
  leg: 'pierna',
  legs: 'piernas',
  calf: 'gemelo',
  calves: 'gemelos',
  chest: 'pecho',
  shoulder: 'hombro',
  shoulders: 'hombros',
  back: 'espalda',
  hip: 'cadera',
  glute: 'glúteo',
  glutes: 'glúteos',
  hamstring: 'femoral',
  hamstrings: 'femoral',
  quad: 'cuádriceps',
  quads: 'cuádriceps',
  ab: 'abdominal',
  abs: 'abdominales',
  oblique: 'oblicuo',
  obliques: 'oblicuos',
  wrist: 'muñeca',
  neck: 'cuello',
  knee: 'rodilla',
  knees: 'rodillas',
  toe: 'puntillas',
  forearm: 'antebrazo',
  bicep: 'bíceps',
  biceps: 'bíceps',
  tricep: 'tríceps',
  triceps: 'tríceps',
  delt: 'deltoides',
  deltoid: 'deltoides',
  lat: 'dorsal',
  front: 'frontal',
  rear: 'posterior',
  side: 'lateral',
  lateral: 'lateral',
  overhead: 'por encima de la cabeza',
  high: 'alto',
  low: 'bajo',
  floor: 'en el suelo',
  wall: 'en la pared',
  full: 'completo',
  half: 'medio',
  wide: 'ancho',
  cross: 'cruzado',
  crossover: 'cruce',
  rope: 'con cuerda',
  rotation: 'rotación',
  twisting: 'con giro',
  isometric: 'isométrico',
  static: 'estático',
  sumo: 'sumo',
  romanian: 'rumano',
  arnold: 'Arnold',
  cuban: 'cubana',
  preacher: 'predicador',
  hammer: 'martillo',
  spider: 'araña',
  frog: 'rana',
  cossack: 'cosaco',
  bulgarian: 'búlgara',
  adductor: 'aductor',
  abductor: 'abductor',
  adduction: 'aducción',
  abduction: 'abducción',
  palm: 'palma',
  palms: 'palmas',
  upper: 'superior',
  inner: 'interno',
  outer: 'externo',
  external: 'externo',
  internal: 'interno',
  lower: 'inferior',
  behind: 'detrás',
  slam: 'lanzamiento',
  lift: 'elevación',
  planche: 'plancha',
  pike: 'pica',
  hang: 'suspendido',
  hanging: 'colgado',
  suspended: 'suspendido',
  stance: 'postura',
  march: 'marcha',
  climber: 'escalador',
  windmill: 'molino',
  around: 'alrededor',
  world: 'del mundo',
  crawl: 'reptación',
  hold: 'isometría',
  bodyweight: 'peso corporal',
  exercise: '',
  male: '',
  female: '',
  and: 'y',
  to: 'a',
  with: 'con',
  on: 'en',
  the: '',
  of: 'de',
  a: '',
  from: 'desde',
  against: 'contra',
  over: '',
  bicycle: 'bicicleta',
  vertical: 'vertical',
  horizontal: 'horizontal',
  diagonal: 'diagonal',
  static: 'estático',
  dynamic: 'dinámico',
  forward: 'adelante',
  backward: 'atrás',
  up: 'arriba',
  down: 'abajo',
  in: 'dentro',
  out: 'fuera',
  under: 'bajo',
  both: 'ambas',
  between: 'entre',
  bench: 'banco',
  benches: 'bancos',
  both: 'ambas',
  each: 'cada',
  legs: 'piernas',
  parallel: 'paralelas',
  bars: 'barras',
}

const cap = (s) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : s)

export function traducirNombre(original) {
  let s = String(original).toLowerCase().trim()
  // Normaliza: guiones → espacio, quita paréntesis (deja su contenido), colapsa.
  s = s.replace(/[-–]/g, ' ').replace(/[()]/g, ' ').replace(/\s+/g, ' ').trim()
  s = ' ' + s + ' '

  // 1) Extraer equipo → sufijo.
  const sufijos = []
  for (const [re, es] of EQUIPO) {
    if (re.test(s)) {
      sufijos.push(es)
      s = s.replace(re, ' ')
    }
  }

  // 2) Frases de movimiento (más largas primero).
  const frasesOrden = [...FRASES].sort((a, b) => b[0].length - a[0].length)
  for (const [en, es] of frasesOrden) {
    s = s.replace(new RegExp('\\b' + en.replace(/ /g, '\\s+') + '\\b', 'g'), ` ${es} `)
  }

  // 3) Palabras sueltas restantes (solo las aún en inglés).
  const tokens = s.split(/\s+/).filter(Boolean).map((t) => {
    if (Object.prototype.hasOwnProperty.call(PALABRAS, t)) return PALABRAS[t]
    return t // desconocida: se queda igual
  })

  let nombre = tokens.filter(Boolean).join(' ').replace(/\s+/g, ' ').trim()
  if (sufijos.length) nombre += ' ' + [...new Set(sufijos)].join(' ')
  // Colapsa preposiciones repetidas ("con con", "en en", "de de").
  nombre = nombre
    .replace(/\b(con|en|de|a)\s+\1\b/g, '$1')
    .replace(/\s+/g, ' ')
    .trim()
  return cap(nombre)
}
